trigger:
  branches:
    include:
      - main
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsServiceConnection: 'aws-oidc-federation'
  awsRegion: 'us-east-1'
  s3TemplatePath: '$(System.DefaultWorkingDirectory)/s3-bucket.yaml'
  ec2TemplatePath: '$(System.DefaultWorkingDirectory)/ec2-tomcat.yaml'
  bucketName: 'mintuminuteonline-bucket-20250706'
  s3StackName: 'LoginAppS3Stack'
  ec2StackName: 'LoginAppEC2Stack'
  keyName: 'cfn-keypair'

jobs:
  - job: DeployS3Bucket
    displayName: 'Deploy S3 Bucket'
    steps:
      - checkout: self
        displayName: 'Checkout GitHub Repository'
      - task: AWSShellScript@1
        displayName: 'Check and Delete Stuck S3 Stack'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            echo "Checking stack status: $(s3StackName)"
            stack_status=$(aws cloudformation describe-stacks --stack-name $(s3StackName) --region $(awsRegion) --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DOES_NOT_EXIST")
            if [[ "$stack_status" == "ROLLBACK_FAILED" || "$stack_status" == "ROLLBACK_COMPLETE" ]]; then
              echo "Stack is in $stack_status state. Attempting to delete..."
              aws cloudformation delete-stack --stack-name $(s3StackName) --region $(awsRegion)
              aws cloudformation wait stack-delete-complete --stack-name $(s3StackName) --region $(awsRegion) || echo "Stack deletion may require manual cleanup"
            else
              echo "Stack status: $stack_status"
            fi
      - task: AWSShellScript@1
        displayName: 'Validate S3 CloudFormation Template'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            aws cloudformation validate-template --template-body file://$(s3TemplatePath)
      - task: AWSShellScript@1
        displayName: 'Deploy S3 CloudFormation Stack'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            echo "Deploying S3 stack: $(s3StackName) with bucket name: $(bucketName)"
            aws cloudformation deploy \
              --template-file $(s3TemplatePath) \
              --stack-name $(s3StackName) \
              --parameter-overrides BucketName=$(bucketName) \
              --no-fail-on-empty-changeset || \
            { echo "Deployment failed. Fetching stack events..."; \
              aws cloudformation describe-stack-events --stack-name $(s3StackName) --region $(awsRegion); \
              exit 1; }
  - job: ValidateAndDeployEC2
    displayName: 'Validate and Deploy EC2 Instance'
    dependsOn: DeployS3Bucket
    condition: succeeded()
    steps:
      - checkout: self
        displayName: 'Checkout GitHub Repository'
      - task: AWSShellScript@1
        displayName: 'Check and Delete Stuck EC2 Stack'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            echo "Checking stack status: $(ec2StackName)"
            stack_status=$(aws cloudformation describe-stacks --stack-name $(ec2StackName) --region $(awsRegion) --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DOES_NOT_EXIST")
            if [[ "$stack_status" == "ROLLBACK_FAILED" || "$stack_status" == "ROLLBACK_COMPLETE" ]]; then
              echo "Stack is in $stack_status state. Attempting to delete..."
              aws cloudformation delete-stack --stack-name $(ec2StackName) --region $(awsRegion)
              aws cloudformation wait stack-delete-complete --stack-name $(ec2StackName) --region $(awsRegion) || echo "Stack deletion may require manual cleanup"
            else
              echo "Stack status: $stack_status"
            fi
      - task: AWSShellScript@1
        displayName: 'Validate EC2 CloudFormation Template'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            aws cloudformation validate-template --template-body file://$(ec2TemplatePath)
      - task: AWSShellScript@1
        displayName: 'Deploy EC2 CloudFormation Stack'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            echo "Deploying EC2 stack: $(ec2StackName) with bucket name: $(bucketName)"
            aws cloudformation deploy \
              --template-file $(ec2TemplatePath) \
              --stack-name $(ec2StackName) \
              --parameter-overrides BucketName=$(bucketName) KeyName=$(keyName) \
              --capabilities CAPABILITY_IAM \
              --no-fail-on-empty-changeset || \
            { echo "Deployment failed. Fetching stack events..."; \
              aws cloudformation describe-stack-events --stack-name $(ec2StackName) --region $(awsRegion); \
              exit 1; }
  - job: CompileAndUploadToS3
    displayName: 'Compile Java Servlet and Upload Files to S3'
    dependsOn: ValidateAndDeployEC2
    condition: succeeded()
    steps:
      - checkout: self
        displayName: 'Checkout GitHub Repository'
        fetchDepth: 0
      - task: JavaToolInstaller@0
        displayName: 'Install Java 11'
        inputs:
          version: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: Bash@3
        displayName: 'Download Servlet API and Compile LoginServlet.java'
        inputs:
          targetType: 'inline'
          script: |
            mkdir -p $(System.DefaultWorkingDirectory)/WebContent/WEB-INF/classes/com/example
            wget https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar -O $(System.DefaultWorkingDirectory)/servlet-api.jar
            echo "Listing source files:"
            ls -R $(System.DefaultWorkingDirectory)/src
            if [ ! -f "$(System.DefaultWorkingDirectory)/src/LoginServlet.java" ]; then
              echo "Error: LoginServlet.java not found in src/"
              exit 1
            fi
            javac -cp $(System.DefaultWorkingDirectory)/servlet-api.jar -sourcepath $(System.DefaultWorkingDirectory)/src -d $(System.DefaultWorkingDirectory)/WebContent/WEB-INF/classes/com/example $(System.DefaultWorkingDirectory)/src/LoginServlet.java 2> /tmp/javac.log
            if [ $? -ne 0 ]; then
              echo "Compilation error details:"
              cat /tmp/javac.log
              exit 1
            fi
            if [ -f "$(System.DefaultWorkingDirectory)/WebContent/WEB-INF/classes/com/example/LoginServlet.class" ]; then
              echo "Compilation successful: LoginServlet.class created"
            else
              echo "Error: Compilation failed - LoginServlet.class not found"
              exit 1
            fi
      - task: AWSShellScript@1
        displayName: 'Upload Files to S3'
        inputs:
          awsCredentials: '$(awsServiceConnection)'
          regionName: '$(awsRegion)'
          scriptType: 'inline'
          inlineScript: |
            if [ -z "$(bucketName)" ]; then
              echo "Error: bucketName variable is empty or unset"
              exit 1
            fi
            echo "Uploading files to S3 bucket: $(bucketName)"
            echo "Listing files in WebContent:"
            ls -R $(System.DefaultWorkingDirectory)/WebContent
            for file in WebContent/login.jsp WebContent/welcome.jsp WebContent/study.jsp WebContent/WEB-INF/web.xml WebContent/WEB-INF/classes/com/example/LoginServlet.class; do
              if [ -f "$(System.DefaultWorkingDirectory)/$file" ]; then
                echo "Uploading $file"
                aws s3 cp $(System.DefaultWorkingDirectory)/$file s3://$(bucketName)/$file
              else
                echo "Error: File $file not found"
                exit 1
              fi
            done
