AWSTemplateFormatVersion: '2010-09-09'
Description: Simple AWS CloudFormation template to create an S3 bucket with versioning and public access blocked.

Parameters:
  BucketName:
    Type: String
    Description: Unique name for the S3 bucket (must be globally unique and lowercase).
    ConstraintDescription: Bucket name must be lowercase, 3-63 characters, and globally unique.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Purpose
          Value: GeneralStorage

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn